live_config_reload: true
import:
  - ~/.config/alacritty/themes/noirbuddy.yml
window:
  dimensions:
    columns: 100
    lines: 85
  decorations_theme_variant: Dark
  decorations: transparent
  startup_mode: Windowed
  dynamic_padding: true
  padding:
    x: 0
    y: 25
font:
  normal:
    family: "FiraCode Nerd Font"
    style: Regular
  size: 12
shell:
  program: /opt/homebrew/bin/fish
  args:
    - -l
    - -c
    - "tmux attach || tmux"
env:
  TERM: xterm-256color
