live_config_reload: true

window:
  # Window dimensions (changes require restart)
  #
  # Specified in number of columns/lines, not pixels. If both are zero this
  # setting is ignored.
  dimensions:
    columns: 100
    lines: 85

  # Window padding (changes require restart)
  #
  # Blank space added around the window in pixels. This padding is not scaled by
  # DPI and the specified value is always added at both opposing sides.
  padding:
    x: 10
    y: 10

  # Spread additional padding evenly around the terminal content.
  dynamic_padding: false

  # Window decorations
  #
  # Available values:
  # - full: borders and title bar
  # - none: neither borders nor title bar
  # - transparent: title bar, transparent background and title bar buttons
  # - buttonless: title bar, transparent background, but no title bar buttons
  decorations: full

  # Startup Mode (changes require restart)
  #
  # Values for `startup_mode`:
  #   - Windowed
  #   - Maximized
  #   - Fullscreen
  #
  # Values for `startup_mode` (macOS only):
  #   - SimpleFullscreen
  startup_mode: Windowed

# Font configuration (changes require restart)
font:
  # The normal (roman) font face to use.
  # Style can be specified to pick a specific face.
  normal:
    family: "Input Mono"
    style: Regular
    antialias: false

  bold:
    family: "Input Mono"
    style: Regular
    antialias: false

  italic:
    family: "Input Mono"
    style: Regular
    antialias: false

  # Point size of the font
  size: 12.0

# Colors (Ayu Dark)
colors:
  # Default colors
  primary:
    background: '0x0f1419'
    foreground: '0xe6e1cf'

  # Normal colors
  normal:
    black:   '0x000000'
    red:     '0xf34a4a'
    green:   '0xbae67e'
    yellow:  '0xffee99'
    blue:    '0x73d0ff'
    magenta: '0xd4bfff'
    cyan:    '0x83CEC6'
    white:   '0xf2f2f2'

  # Bright colors
  bright:
    black:   '0x737d87'
    red:     '0xff3333'
    green:   '0xc2d94c'
    yellow:  '0xe7c547'
    blue:    '0x59c2ff'
    magenta: '0xb77ee0'
    cyan:    '0x5ccfe6'
    white:   '0xffffff'
