live_config_reload: true

window:
  # Window dimensions (changes require restart)
  #
  # Specified in number of columns/lines, not pixels. If both are zero this
  # setting is ignored.
  dimensions:
    columns: 100
    lines: 85

  # Window padding (changes require restart)
  #
  # Blank space added around the window in pixels. This padding is not scaled by
  # DPI and the specified value is always added at both opposing sides.
  # padding:
    # x: 10
    # y: 10

  # Spread additional padding evenly around the terminal content.
  dynamic_padding: true

  # Window decorations
  #
  # Available values:
  # - full: borders and title bar
  # - none: neither borders nor title bar
  # - transparent: title bar, transparent background and title bar buttons
  # - buttonless: title bar, transparent background, but no title bar buttons
  decorations: buttonless

  # Startup Mode (changes require restart)
  #
  # Values for `startup_mode`:
  #   - Windowed
  #   - Maximized
  #   - Fullscreen
  #
  # Values for `startup_mode` (macOS only):
  #   - SimpleFullscreen
  startup_mode: Windowed

# Font configuration (changes require restart)
font:
  # The normal (roman) font face to use.
  # Style can be specified to pick a specific face.
  normal:
    family: "FiraCode Nerd Font"
    style: Regular

  # Point size of the font
  size: 12

shell:
  program: /opt/homebrew/bin/fish
  args:
    - -l
    - -c
    - "tmux attach || tmux"

schemes:
  ayu:
    dark: &ayu_dark # Default colors
      primary:
        background: "0x0D1017"
        foreground: "0xBFBDB6"

      # Normal colors
      normal:
        black: "0x000000"
        blue: "0x73d0ff"
        cyan: "0x83CEC6"
        green: "0xbae67e"
        magenta: "0xd4bfff"
        red: "0xf34a4a"
        white: "0xf2f2f2"
        yellow: "0xffee99"

      # Bright colors
      bright:
        black: "0x737d87"
        blue: "0x59c2ff"
        cyan: "0x5ccfe6"
        green: "0xc2d94c"
        magenta: "0xb77ee0"
        red: "0xff3333"
        white: "0xffffff"
        yellow: "0xe7c547"

    light: &ayu_light
      primary:
        background: "0xfafafa"
        foreground: "0x5b6672"

      # Normal colors
      normal:
        black: "0x000000"
        blue: "0x41a5d9"
        cyan: "0x4dbf98"
        green: "0x76cc00"
        magenta: "0x9965cc"
        red: "0xf2590b"
        white: "0xc7c7c7"
        yellow: "0xf29717"

      # Bright colors
      bright:
        black: "0x676767"
        blue: "0x6871ff"
        cyan: "0x56d9ad"
        green: "0xa3d900"
        magenta: "0xa37acc"
        red: "0xd6646a"
        white: "0xfeffff"
        yellow: "0xe7c446"

  rose_pine: &rose_pine
    primary:
      background: "0x191724"
      foreground: "0xe0def4"
    cursor:
      text: "0xe0def4"
      cursor: "0x524f67"
    vi_mode_cursor:
      text: "0xe0def4"
      cursor: "0x524f67"
    line_indicator:
      foreground: None
      background: None
    selection:
      text: "0xe0def4"
      background: "0x403d52"
    normal:
      black: "0x26233a"
      red: "0xeb6f92"
      green: "0x31748f"
      yellow: "0xf6c177"
      blue: "0x9ccfd8"
      magenta: "0xc4a7e7"
      cyan: "0xebbcba"
      white: "0xe0def4"
    bright:
      black: "0x6e6a86"
      red: "0xeb6f92"
      green: "0x31748f"
      yellow: "0xf6c177"
      blue: "0x9ccfd8"
      magenta: "0xc4a7e7"
      cyan: "0xebbcba"
      white: "0xe0def4"
    hints:
      start:
        foreground: "#908caa"
        background: "#1f1d2e"
      end:
        foreground: "#6e6a86"
        background: "#1f1d2e"

  gruvbox:
    light:
      hard: &gruvbox_light_hard
        primary:
          background: "0xf9f5d7"
          foreground: "0x3c3836"

        normal:
          black: "0xfbf1c7"
          red: "0xcc241d"
          green: "0x98971a"
          yellow: "0xd79921"
          blue: "0x458588"
          magenta: "0xb16286"
          cyan: "0x689d6a"
          white: "0x7c6f64"

        bright:
          black: "0x928374"
          red: "0x9d0006"
          green: "0x79740e"
          yellow: "0xb57614"
          blue: "0x076678"
          magenta: "0x8f3f71"
          cyan: "0x427b58"
          white: "0x3c3836"
    dark:
      medium: &gruvbox_dark_medium
        primary:
          background: "0x282828"
          foreground: "0xdfbf8e"

        normal:
          black: "0x665c54"
          red: "0xea6962"
          green: "0xa9b665"
          yellow: "0xe78a4e"
          blue: "0x7daea3"
          magenta: "0xd3869b"
          cyan: "0x89b482"
          white: "0xdfbf8e"

        bright:
          black: "0x928374"
          red: "0xea6962"
          green: "0xa9b665"
          yellow: "0xe3a84e"
          blue: "0x7daea3"
          magenta: "0xd3869b"
          cyan: "0x89b482"
          white: "0xdfbf8e"

      hard: &gruvbox_dark_hard
        primary:
          background: "0x1d2021"
          foreground: "0xd5c4a1"

        normal:
          black: "0x1d2021"
          red: "0xfb4934"
          green: "0xb8bb26"
          yellow: "0xfabd2f"
          blue: "0x83a598"
          magenta: "0xd3869b"
          cyan: "0x8ec07c"
          white: "0xd5c4a1"

        bright:
          black: "0x665c54"
          red: "0xfb4934"
          green: "0xb8bb26"
          yellow: "0xfabd2f"
          blue: "0x83a598"
          magenta: "0xd3869b"
          cyan: "0x8ec07c"
          white: "0xfbf1c7"

colors: *rose_pine
