live_config_reload: true

import:
  - ~/.config/alacritty/themes/rose-pine.yml

window:
  dimensions:
    columns: 100
    lines: 85

  decorations: none
  decorations_theme_variant: Dark

  startup_mode: Windowed

font:
  normal:
    family: "FiraCode Nerd Font"
    style: Regular
  size: 12

shell:
  program: /opt/homebrew/bin/fish
  args:
    - -l
    - -c
    - "tmux attach || tmux"
