import = ["~/.config/alacritty/themes/monochrome-light.toml"]
live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/opt/homebrew/bin/fish"

[window]
decorations = "transparent"
decorations_theme_variant = "Dark"
dynamic_padding = true
startup_mode = "Windowed"

[window.dimensions]
columns = 100
lines = 85

[window.padding]
x = 0
y = 20
