colors:
  primary:
    background: "0x0D1017"
    foreground: "0xBFBDB6"

    # Normal colors
  normal:
    black: "0x000000"
    blue: "0x73d0ff"
    cyan: "0x83CEC6"
    green: "0xbae67e"
    magenta: "0xd4bfff"
    red: "0xf34a4a"
    white: "0xf2f2f2"
    yellow: "0xffee99"

    # Bright colors
  bright:
    black: "0x737d87"
    blue: "0x59c2ff"
    cyan: "0x5ccfe6"
    green: "0xc2d94c"
    magenta: "0xb77ee0"
    red: "0xff3333"
    white: "0xffffff"
    yellow: "0xe7c547"
