colors:
  primary:
    background: "0xfafafa"
    foreground: "0x5b6672"

    # Normal colors
  normal:
    black: "0x000000"
    blue: "0x41a5d9"
    cyan: "0x4dbf98"
    green: "0x76cc00"
    magenta: "0x9965cc"
    red: "0xf2590b"
    white: "0xc7c7c7"
    yellow: "0xf29717"

    # Bright colors
  bright:
    black: "0x676767"
    blue: "0x6871ff"
    cyan: "0x56d9ad"
    green: "0xa3d900"
    magenta: "0xa37acc"
    red: "0xd6646a"
    white: "0xfeffff"
    yellow: "0xe7c446"

