[colors.bright]
black = "0x535353"
blue = "0xf5f5f5"
cyan = "0xb4b4b4"
green = "0x00FF00"
magenta = "0xb4b4b4"
red = "0xFF0000"
white = "0xffffff"
yellow = "0xf5f5f5"

[colors.normal]
black = "0x535353"
blue = "0xf5f5f5"
cyan = "0xb4b4b4"
green = "0x00FF00"
magenta = "0xb4b4b4"
red = "0xFF0000"
white = "0xffffff"
yellow = "0xf5f5f5"

[colors.primary]
background = "0x000000"
foreground = "0xb4b4b4"
