colors:
  primary:
    background: "0x000000"
    foreground: "0xb4b4b4"

  # Normal colors
  normal:
    black:   "0x535353"
    blue:    "0xf5f5f5"
    cyan:    "0xb4b4b4"
    green:   "0x737373"
    magenta: "0xb4b4b4"
    red:     "0xC2B280" # primary
    white:   "0xffffff"
    yellow:  "0xf5f5f5"

  bright:
    black:   "0x535353"
    blue:    "0xf5f5f5"
    cyan:    "0xb4b4b4"
    green:   "0x737373"
    magenta: "0xb4b4b4"
    red:     "0xC2B280" # primary
    white:   "0xffffff"
    yellow:  "0xf5f5f5"
