tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

brew "ctags"
brew "direnv"
brew "exercism"
brew "fzf"
brew "git"
brew "mas"
brew "neovim"
brew "the_silver_searcher"
brew "z"
brew "zsh"

cask "alfred"
cask "bartender"
cask "calibre"
cask "dash"
cask "docker"
cask "firefox"
cask "firefox-developer-edition"
cask "flux"
cask "focus"
cask "google-chrome"
cask "google-chrome-canary"
cask "hammerspoon"
cask "imagealpha"
cask "imageoptim"
cask "iterm2"
cask "keka"
cask "postman"
cask "spotify"
cask "tor-browser"

mas "Xcode", id: 497799835
