#!/bin/sh
set -e

readonly RED=$(tput setab 1)
readonly NORMAL=$(tput sgr0)
readonly CONVENTIONAL_COMMIT_REGEX="^(feat|fix|docs|build|ci|perf|style|refactor|test|chore)(\(.+\))?\!?:"

readonly msg=$(< $1)

if [[ ! $msg =~ $CONVENTIONAL_COMMIT_REGEX ]]; then
    echo "$RED ERROR $NORMAL Commit message should follow the conventional commit structure."
    exit 1
fi

exit 0
