#!/bin/sh
set -e

RED="$(tput setab 1)"
NORMAL="$(tput sgr0)"

if ! head -1 "$1" | grep -qE "^(feat|fix|chore|docs|test|style|refactor|perf|build|ci|revert)(\(.+?\))?: .{1,}$"; then
    echo "$RED ERROR $NORMAL Commit message should follow the conventional commit structure." >&2
    exit 1
fi

if ! head -1 "$1" | grep -qE "^.{1,88}$"; then
    echo "$RED ERROR $NORMAL Commit message is too long." >&2
    exit 1
fi
exit 0
