#!/bin/sh

readonly RED=$(tput setab 1)
readonly NORMAL=$(tput sgr0)
readonly CONFLICT_MARKERS='<<<<<<<|=======|>>>>>>>'
readonly CHECK=$(git diff --staged | grep "^+" | grep -Ei "$CONFLICT_MARKERS" -c)

if [ "$CHECK" -gt 0 ]
then
    echo "$RED ERROR $NORMAL Conflict markers sill preset in the following files:"
    git diff --staged --name-only -G"$CONFLICT_MARKERS"
    exit 1
fi

if ! gitleaks protect --no-banner --staged --redact &>/dev/null; then
  echo "$RED ERROR $NORMAL gitleaks has detected sensitive information in your changes."
  exit 1
fi

exit 0
