-- Ayu palette and highlight mappings adapted from Shatur/neovim-ayu.
local colors = vim.o.background == "light" and {
    accent = "#FFAA33",
    bg = "#F8F9FA",
    comment = "#ABADB1",
    constant = "#A37ACC",
    entity = "#399EE6",
    error = "#E65050",
    fg = "#5C6166",
    fg_idle = "#8A9199",
    func = "#F2AE49",
    guide_normal = "#E4E6E9",
    gutter_normal = "#CCCFD3",
    keyword = "#FA8D3E",
    line = "#E7EAED",
    lsp_parameter = "#C788CE",
    markup = "#F07171",
    operator = "#ED9366",
    panel_bg = "#F3F4F5",
    panel_border = "#F0F0F0",
    panel_shadow = "#D3D4D5",
    regexp = "#4CBF99",
    selection_inactive = "#E7EEF7",
    special = "#E6BA7E",
    string = "#86B300",
    tag = "#55B4D4",
    vcs_added = "#6CBF43",
    vcs_added_bg = "#E0E7CD",
    vcs_modified = "#478ACC",
    vcs_removed = "#FF7383",
    vcs_removed_bg = "#F9EBE4",
    warning = "#FA8D3E",
} or {
    accent = "#E6B450",
    bg = "#0B0E14",
    comment = "#636A72",
    constant = "#D2A6FF",
    entity = "#59C2FF",
    error = "#D95757",
    fg = "#BFBDB6",
    fg_idle = "#565B66",
    func = "#FFB454",
    guide_normal = "#1E222A",
    gutter_normal = "#454B55",
    keyword = "#FF8F40",
    line = "#11151C",
    lsp_parameter = "#CB9FF8",
    markup = "#F07178",
    operator = "#F29668",
    panel_bg = "#0F131A",
    panel_border = "#000000",
    panel_shadow = "#05070A",
    regexp = "#95E6CB",
    selection_inactive = "#122132",
    special = "#E6B673",
    string = "#AAD94C",
    tag = "#39BAE6",
    vcs_added = "#7FD962",
    vcs_added_bg = "#1D2214",
    vcs_modified = "#73B8FF",
    vcs_removed = "#F26D78",
    vcs_removed_bg = "#2D2220",
    warning = "#FF8F40",
}

vim.o.termguicolors = true
vim.g.colors_name = "ayu"

local terminal_colors = {
    colors.bg,
    colors.markup,
    colors.string,
    colors.accent,
    colors.tag,
    colors.constant,
    colors.regexp,
    colors.fg,
    colors.fg_idle,
    colors.error,
    colors.string,
    colors.accent,
    colors.tag,
    colors.constant,
    colors.regexp,
    colors.comment,
}
for index, color in ipairs(terminal_colors) do
    vim.g["terminal_color_" .. index - 1] = color
end
vim.g.terminal_color_background = colors.bg
vim.g.terminal_color_foreground = colors.fg

local groups = {
    Normal = { fg = colors.fg, bg = "NONE" },
    NormalNC = { bg = "NONE" },
    NormalFloat = { bg = colors.bg },
    FloatBorder = { fg = colors.comment },
    FloatTitle = { fg = colors.fg },
    ColorColumn = { bg = colors.line },
    Cursor = { fg = colors.bg, bg = colors.fg },
    CursorColumn = { bg = colors.line },
    CursorLine = { bg = colors.line },
    CursorLineNr = { fg = colors.accent, bg = colors.line },
    LineNr = { fg = colors.guide_normal },
    Directory = { fg = colors.func },
    ErrorMsg = { fg = colors.error },
    WinSeparator = { fg = colors.panel_border, bg = colors.bg },
    VertSplit = { link = "WinSeparator" },
    Folded = { fg = colors.fg_idle, bg = colors.panel_bg },
    FoldColumn = { bg = "NONE" },
    SignColumn = { bg = "NONE" },
    MatchParen = { sp = colors.func, underline = true },
    ModeMsg = { fg = colors.string },
    MoreMsg = { fg = colors.string },
    NonText = { fg = colors.guide_normal },
    Pmenu = { fg = colors.fg, bg = colors.selection_inactive },
    PmenuSel = { fg = colors.fg, bg = colors.selection_inactive, reverse = true },
    Question = { fg = colors.string },
    Search = { fg = colors.bg, bg = colors.constant },
    CurSearch = { fg = colors.bg, bg = colors.special },
    IncSearch = { fg = colors.keyword, bg = colors.selection_inactive },
    SpecialKey = { fg = colors.selection_inactive },
    SpellCap = { sp = colors.tag, undercurl = true },
    SpellLocal = { sp = colors.keyword, undercurl = true },
    SpellBad = { sp = colors.error, undercurl = true },
    SpellRare = { sp = colors.regexp, undercurl = true },
    StatusLine = { fg = colors.fg, bg = colors.panel_bg },
    StatusLineNC = { fg = colors.fg_idle, bg = colors.panel_bg },
    WildMenu = { fg = colors.fg, bg = colors.markup },
    TabLine = { fg = colors.comment, bg = colors.panel_shadow },
    TabLineFill = { fg = colors.fg, bg = colors.panel_border },
    TabLineSel = { fg = colors.fg, bg = colors.bg },
    Title = { fg = colors.keyword },
    Visual = { bg = colors.selection_inactive },
    WarningMsg = { fg = colors.warning },

    Comment = { fg = colors.comment, italic = true },
    Constant = { fg = colors.constant },
    String = { fg = colors.string },
    Identifier = { fg = colors.entity },
    Function = { fg = colors.func },
    Statement = { fg = colors.keyword },
    Operator = { fg = colors.operator },
    Exception = { fg = colors.markup },
    PreProc = { fg = colors.accent },
    Type = { fg = colors.entity },
    Structure = { fg = colors.special },
    Special = { fg = colors.accent },
    Delimiter = { fg = colors.special },
    Underlined = { sp = colors.tag, underline = true },
    Ignore = { fg = colors.fg },
    Error = { fg = "#FFFFFF", bg = colors.error },
    Todo = { fg = colors.markup },
    qfLineNr = { fg = colors.keyword },
    qfError = { fg = colors.error },
    Conceal = { fg = colors.comment },
    CursorLineConceal = { fg = colors.guide_normal, bg = colors.line },

    Added = { fg = colors.vcs_added },
    Removed = { fg = colors.vcs_removed },
    Changed = { fg = colors.vcs_modified },
    DiffAdd = { bg = colors.vcs_added_bg },
    DiffAdded = { fg = colors.vcs_added },
    DiffDelete = { bg = colors.vcs_removed_bg },
    DiffRemoved = { fg = colors.vcs_removed },
    DiffText = { bg = colors.gutter_normal },
    DiffChange = { bg = colors.selection_inactive },

    DiagnosticError = { fg = colors.error },
    DiagnosticWarn = { fg = colors.keyword },
    DiagnosticInfo = { fg = colors.tag },
    DiagnosticHint = { fg = colors.regexp },
    DiagnosticUnderlineError = { sp = colors.error, undercurl = true },
    DiagnosticUnderlineWarn = { sp = colors.keyword, undercurl = true },
    DiagnosticUnderlineInfo = { sp = colors.tag, undercurl = true },
    DiagnosticUnderlineHint = { sp = colors.regexp, undercurl = true },
    LspInlayHint = { fg = "#969696" },
    LspSignatureActiveParameter = { italic = true },

    markdownCode = { fg = colors.special },
    ["@property"] = { fg = colors.tag },
    ["@tag"] = { fg = colors.keyword },
    ["@tag.attribute"] = { fg = colors.entity },
    ["@tag.delimiter"] = { link = "Delimiter" },
    ["@type.qualifier"] = { fg = colors.keyword },
    ["@variable"] = { fg = colors.fg },
    ["@variable.builtin"] = { fg = colors.func },
    ["@variable.member"] = { fg = colors.tag },
    ["@variable.parameter"] = { fg = colors.fg },
    ["@module"] = { fg = colors.func },
    ["@markup.heading"] = { fg = colors.keyword },
    ["@keyword.storage"] = { fg = colors.keyword },

    ["@lsp.type.namespace"] = { link = "@module" },
    ["@lsp.type.type"] = { link = "@type" },
    ["@lsp.type.class"] = { link = "@type" },
    ["@lsp.type.enum"] = { link = "@type" },
    ["@lsp.type.interface"] = { link = "@type" },
    ["@lsp.type.struct"] = { link = "@variable.member" },
    ["@lsp.type.parameter"] = { fg = colors.lsp_parameter },
    ["@lsp.type.field"] = { link = "@variable.member" },
    ["@lsp.type.variable"] = { link = "@variable" },
    ["@lsp.type.property"] = { link = "@property" },
    ["@lsp.type.enumMember"] = { link = "@constant" },
    ["@lsp.type.function"] = { link = "@function" },
    ["@lsp.type.method"] = { link = "@function.method" },
    ["@lsp.type.macro"] = { link = "@function.macro" },
    ["@lsp.type.decorator"] = { link = "@function" },
    ["@lsp.mod.constant"] = { link = "@constant" },

    FlashBackdrop = { fg = colors.comment },
    FlashMatch = { fg = colors.bg, bg = colors.warning },
    FlashCurrent = { fg = colors.bg, bg = colors.tag },
    FlashLabel = { fg = "#FFFFFF", bg = colors.error, bold = true },
    FlashCursor = { reverse = true },
}

for group, parameters in pairs(groups) do
    vim.api.nvim_set_hl(0, group, parameters)
end
