# Block ads and other analytics
export ADBLOCK=true
export DISABLE_OPENCOLLECTIVE=true
export DO_NOT_TRACK=1 # https://consoledonottrack.com/

# Set lang
export LANG="en_US.UTF-8"
export LC_ALL="${LANG}"
export LC_CTYPE="${LANG}"

# Disable shell sessions
export SHELL_SESSIONS_DISABLE=1

# Silent direnv
export DIRENV_LOG_FORMAT=""

# https://0x46.net/thoughts/2019/02/01/dotfile-madness/
# For https://stackoverflow.com/a/5084892
export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_CACHE_HOME="${HOME}/Library/Caches"
export XDG_DATA_HOME="${HOME}/.local/share"
export XDG_RUNTIME_DIR="${XDG_DATA_HOME}"
export XDG_CONFIG_DIRS="/etc/xdg:${XDG_CONFIG_HOME}"
export XDG_DATA_DIRS="/usr/local/share:/usr/share:${XDG_DATA_HOME}"

# Output `brew shellenv`
case "$(uname -m)" in
 arm64)
   export HOMEBREW_PREFIX="/opt/homebrew"
   export HOMEBREW_REPOSITORY="${HOMEBREW_PREFIX}";
   ;;
 *)
   export HOMEBREW_PREFIX="/usr/local"
   export HOMEBREW_REPOSITORY="${HOMEBREW_PREFIX}/Homebrew";
   ;;
esac
export HOMEBREW_CELLAR="${HOMEBREW_PREFIX}/Cellar";
export HOMEBREW_SHELLENV_PREFIX="${HOMEBREW_PREFIX}";
export HOMEBREW_DIR="${HOMEBREW_PREFIX}/bin"
export MANPATH="${HOMEBREW_PREFIX}/share/man${MANPATH+:${MANPATH}}:";
export INFOPATH="${HOMEBREW_PREFIX}/share/info:${INFOPATH:-}";
# If it's been more than this number of seconds since Homebrew was last
# updated, automatically run `brew update` before `brew install`.
# 604800 is 1 week in seconds (60 * 60 * 24 * 7).
export HOMEBREW_AUTO_UPDATE_SECS=604800
export HOMEBREW_NO_ANALYTICS=1
export HOMEBREW_INSTALL_CLEANUP=1
export HOMEBREW_CLEANUP_MAX_AGE_DAYS=7 # Decrease from default 120 days
export HOMEBREW_NO_ENV_HINTS=1
export HOMEBREW_NO_EMOJI=1

export EDITOR="nvim"
export VISUAL="${EDITOR}"

# ============================= Set XDG for tools ==============================

# ZSH
export HISTFILE="${ZDOTDIR}/.zsh_history"
export HISTSIZE=10000000
export SAVEHIST=10000000
export ZCOMPDUMP="${XDG_CACHE_HOME}/.zcompdump"
export ZDOTDIR="${XDG_CONFIG_HOME}/zsh"
export ZSH_CACHE_DIR="${XDG_CACHE_HOME}/zsh"
export ZSH_EVALCACHE_DIR="${XDG_DATA_HOME}/zsh"

# Less
export LESSHISTFILE="${XDG_CACHE_HOME}/less/history"
export LESSKEY="${XDG_CONFIG_HOME}/less/keys"

# rupa/z
export _Z_DATA="${XDG_DATA_HOME}/z/z.txt"

# NeoVim
export NVIM_COC_LOG_FILE="${XDG_CACHE_HOME}/coc-nvim.log"

# Asdf
export ASDF_CONFIG_DIR="${XDG_CONFIG_HOME}/asdf"
export ASDF_CONFIG_FILE="${ASDF_CONFIG_DIR}/asdfrc"
export ASDF_DATA_DIR="${XDG_DATA_HOME}/asdf"
export ASDF_GEM_DEFAULT_PACKAGES_FILE="${ASDF_CONFIG_DIR}/default-gems"
export ASDF_NPM_DEFAULT_PACKAGES_FILE="${ASDF_CONFIG_DIR}/default-npm-packages"
export ASDF_PYTHON_DEFAULT_PACKAGES_FILE="${ASDF_CONFIG_DIR}/default-python-packages"

# GPG
export GNUPGHOME="${XDG_CONFIG_HOME}/gnupg"
export GPG_TTY="${TTY}"

# Node.js
export BABEL_CACHE_PATH="${XDG_CACHE_HOME}/babel.json"
export NODE_REPL_HISTORY="${XDG_CACHE_HOME}/node/repl_history"
export NPM_CONFIG_CACHE="${XDG_CACHE_HOME}/npm"
export NPM_CONFIG_DEVDIR="${XDG_CACHE_HOME}/node-gyp"
export NPM_CONFIG_USERCONFIG="${XDG_CONFIG_HOME}/npm/config"

# Elm
export ELM_HOME="${XDG_CACHE_HOME}/elm"

# Ruby
export GEMRC="${XDG_CONFIG_HOME}/gem/config.yml"
export GEM_HOME="${XDG_DATA_HOME}/gem"
export GEM_SPEC_CACHE="${GEM_HOME}/specs"
export IRBRC="${XDG_CONFIG_HOME}/irb/config"
export BUNDLE_USER_HOME="${XDG_CONFIG_HOME}/bundler"
export BUNDLE_USER_CONFIG="${BUNDLE_USER_HOME}/config.yml"
export BUNDLE_USER_CACHE="${XDG_CACHE_HOME}/bundler"
export BUNDLE_USER_PLUGIN="${XDG_DATA_HOME}/bundler"

# Rust
export CARGO_CACHE_DIR="${XDG_CACHE_HOME}/cargo"
export CARGO_CONFIG_DIR="${XDG_CONFIG_HOME}/cargo"
export RUSTUP_HOME"${XDG_DATA_HOME}/rustup"
