# Block ADs and other analytics
export ADBLOCK=true
export DISABLE_OPENCOLLECTIVE=true
export DO_NOT_TRACK=1 # https://consoledonottrack.com/
export NG_CLI_ANALYTICS=false # https://github.com/angular/angular-cli/blob/master/docs/design/analytics.md

export LANG="en_US.UTF-8"
export LC_ALL=$LANG
export LC_CTYPE=$LANG

# Disable shell sessions
export SHELL_SESSIONS_DISABLE=1

# Silent direnv
export DIRENV_LOG_FORMAT=""

# https://0x46.net/thoughts/2019/02/01/dotfile-madness/
export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share
export XDG_RUNTIME_DIR=$XDG_DATA_HOME
export XDG_CONFIG_DIRS=/etc/xdg:$XDG_CONFIG_HOME
export XDG_DATA_DIRS=/usr/local/share:/usr/share:$XDG_DATA_HOME

# Output `brew shellenv`
export HOMEBREW_PREFIX="/opt/homebrew";
export HOMEBREW_CELLAR="/opt/homebrew/Cellar";
export HOMEBREW_REPOSITORY="/opt/homebrew";
export HOMEBREW_SHELLENV_PREFIX="/opt/homebrew";
export MANPATH="/opt/homebrew/share/man${MANPATH+:$MANPATH}:";
export INFOPATH="/opt/homebrew/share/info:${INFOPATH:-}";
# If it's been more than this number of seconds since Homebrew was last
# updated, automatically run `brew update` before `brew install`.
# 604800 is 1 week in seconds (60 * 60 * 24 * 7).
export HOMEBREW_AUTO_UPDATE_SECS=604800
export HOMEBREW_NO_ANALYTICS=1
export HOMEBREW_INSTALL_CLEANUP=1
export HOMEBREW_DIR=$HOMEBREW_PREFIX/bin

export PATH=$HOMEBREW_PREFIX/bin:$HOMEBREW_PREFIX/sbin:$PATH
export PATH=$HOMEBREW_PREFIX/opt/fzf/bin:$PATH
export PATH=$XDG_DATA_HOME/shell:$PATH

export EDITOR=nvim
export VISUAL=nvim

export GPG_TTY=$TTY

# ============================= Set XDG for tools ==============================
export LESSHISTFILE=$XDG_CONFIG_HOME/less/history
export LESSKEY=$XDG_CONFIG_HOME/less/keys

export ZDOTDIR=$XDG_CONFIG_HOME/zsh
export ZSH_EVALCACHE_DIR=$XDG_DATA_HOME/zsh
export ZSH_CACHE_DIR=$XDG_CACHE_HOME/zsh
export ZCOMPDUMP=$ZDOTDIR/.zcompdump
export FPATH=$ZDOTDIR/functions:$FPATH
export HISTFILE=$ZDOTDIR/.zsh_history
export HISTSIZE=10000000
export SAVEHIST=$HISTSIZE

export _Z_DATA=$XDG_CACHE_HOME/z/z.txt

export ASDF_CONFIG_DIR=$XDG_CONFIG_HOME/asdf
export ASDF_DEFAULT_TOOL_VERSIONS_FILENAME=$ASDF_CONFIG_DIR/tool-versions
export ASDF_CONFIG_FILE=$ASDF_CONFIG_DIR/asdfrc
export ASDF_DATA_DIR=$XDG_DATA_HOME/asdf
export ASDF_PYTHON_DEFAULT_PACKAGES_FILE=$ASDF_CONFIG_DIR/default-python-packages
export ASDF_NPM_DEFAULT_PACKAGES_FILE=$ASDF_CONFIG_DIR/default-npm-packages
export ASDF_GEM_DEFAULT_PACKAGES_FILE=$ASDF_CONFIG_DIR/default-gems

export GNUPGHOME=$XDG_CONFIG_HOME/gnupg

export NPM_CONFIG_USERCONFIG=$XDG_CONFIG_HOME/npm/config
export NPM_CONFIG_CACHE=$XDG_CACHE_HOME/npm
export NPM_CONFIG_TMP=$XDG_RUNTIME_DIR/npm
export NODE_REPL_HISTORY=$XDG_DATA_HOME/node/repl_history
export NPM_CONFIG_DEVDIR=$XDG_CACHE_HOME/node-gyp

export ELM_HOME=$XDG_CACHE_HOME/elm

export BABEL_CACHE_PATH=$XDG_CACHE_HOME/babel.json

# Disable virtual env prompt prefix
export VIRTUAL_ENV_DISABLE_PROMPT=1

export IPYTHONDIR=$XDG_CONFIG_HOME/jupyter
export JUPYTER_CONFIG_DIR=$XDG_CONFIG_HOME/jupyter
export CONDARC=$XDG_CONFIG_HOME/conda/condarc
export PYTHONHISTFILE=$XDG_CACHE_HOME/python/history

export GEMRC=$XDG_CONFIG_HOME/gem/config.yml
export GEM_HOME=$XDG_DATA_HOME/gem
export GEM_SPEC_CACHE=$GEM_HOME/specs
export IRBRC=$XDG_CONFIG_HOME/irb/config
export BUNDLE_USER_HOME=$XDG_CONFIG_HOME/bundler
export BUNDLE_USER_CONFIG=$BUNDLE_USER_HOME/config.yml
export BUNDLE_USER_CACHE=$XDG_CACHE_HOME/bundler
export BUNDLE_USER_PLUGIN=$XDG_DATA_HOME/bundler

export HEX_HOME=$XDG_CACHE_HOME/hex

export DOCKER_CONFIG=$XDG_CONFIG_HOME/docker
