#!/bin/bash

# Toggle this hook on/off with an env variable
[ -z "$ENFORCE_BRANCH_NAME" ] && exit 0

local_branch="$(git branch --show-current)"
valid_branch_regex="^(master|main|(feature|bugfix|production)\/.*)$"

if [[ ! $local_branch =~ $valid_branch_regex ]]
then
  echo "Trying to commit a branch with an invalid name."
  echo "Contract: $valid_branch_regex"
  echo "Change the branch name to start with correct naming and try again."
  exit 1
fi
exit 0
