#!/bin/sh

# Toggle this hook on/off with an env variable
[ -z "$ENFORCE_JIRA_TICKET" ] && exit 0

# http://nsbogan.com/tools/2015/06/04/jira-id-in-git-commit-messages
TICKET=$(git symbolic-ref HEAD | rev | cut -d/ -f1 | rev | grep -o -E "[A-Z]+-[0-9]+")

# If commit message is a fix message, ignore it.
[[ -n "$(cat $1 | grep '^Fix')" ]] && FIX="YES"
[[ -n "$(cat $1 | grep "^${TICKET}")" ]] && TICKET_EXISTS="YES"

if [[ -n "${TICKET}" && -z "${FIX}" && -z "${TICKET_EXISTS}" ]]; then
    echo "A JIRA ticket is required for this commit."
    echo "Add the ticket number and try again."
    sed -i.bak -e "1s/^/${TICKET}: /" $1
fi
exit 0
