[settings]
# Plugins can read the versions files used by other version managers (if enabled by the plugin)
# For example, .nvmrc in the case of nodejs's nvm
legacy_version_file = false

# configure `mise install` to always keep the downloaded archive
always_keep_download = false

# configure how frequently (in minutes) to fetch updated plugin repository changes
# this is updated whenever a new runtime is installed
# (note: this isn't currently implemented but there are plans to add it: https://github.com/jdxcode/mise/issues/128)
# set to 0 to disable updates
plugin_autoupdate_last_check_duration = '0'

# set to true to see full installation output, see `MISE_VERBOSE`
verbose = false
# set to true to ensure .tool-versions will be compatible with asdf, see `MISE_ASDF_COMPAT`
asdf_compat = true
# disable the default shorthands, see `MISE_DISABLE_DEFAULT_SHORTHANDS`
disable_default_shorthands = true
